<?php

use Bitrix\Main\Loader;
use PHPUnit\Framework\TestCase;
use tests\Entity\IblockType\BitrixWrapperTestIBType;
use tests\Entity\IblockType\BitrixWrapperTestIBTypeTest;

class IBlockTypeTest extends TestCase
{
    protected $classOB;

    protected function setUp() : void
    {
        parent::setUp();

        initBitrixCore();

    }

    public function testGetCode()
    {
        $this->assertEquals('BitrixWrapperTestIBType', BitrixWrapperTestIBType::getCode());
        $this->assertEquals('test', BitrixWrapperTestIBTypeTest::getCode());
    }


    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

    }
}