<?php

use Bitrix\Main\Loader;
use PHPUnit\Framework\TestCase;
use tests\Entity\Iblock\BitrixWrapperTestIBlock;
use tests\Entity\IblockType\BitrixWrapperTestIBType;
use tests\Entity\IblockType\BitrixWrapperTestIBTypeTest;

class IBlockTest extends \tests\TestCaseBitrix
{
    protected $classOB;

    public function testGetId() {
        $this->assertIsInt((new BitrixWrapperTestIBlock())->getId());
    }


    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

    }
}