<?php

use Bitrix\Main\Loader;
use PHPUnit\Framework\TestCase;
use tests\Entity\IblockType\BitrixWrapperTestIBType;
use tests\Entity\IblockType\BitrixWrapperTestIBTypeTest;
use tests\TestCaseBitrix;

class IBlockTypeTest extends TestCaseBitrix
{
    protected $classOB;

    public function testGetCode()
    {
        $this->assertEquals('BitrixWrapperTestIBType', (new BitrixWrapperTestIBType())->getCode());
        $this->assertEquals('test', (new BitrixWrapperTestIBTypeTest())->getCode());
    }


    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

    }
}